FROM adoptopenjdk:8u212-b03-jdk-hotspot AS builder

RUN mkdir app

ADD . /app

WORKDIR /app
RUN ./mvnw clean package -Dmaven.test.skip=true
RUN cp -fr /app/target/*.jar /app/target/app.jar

FROM adoptopenjdk:8u212-b03-jre-hotspot
WORKDIR /root/
COPY --from=builder /app/target/app.jar .
docke
CMD ["java", "-jar", "app.jar"]