# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1
executors:
  docker-builder:
    docker:
      - image: circleci/buildpack-deps:stretch

jobs:
  BuildImage:
    executor: docker-builder
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "Building project image"
          command: "docker build -t ${CIRCLE_PROJECT_REPONAME}:latest ."
      - run:
          name: "Archive Docker image"
          command: "docker save -o image.tar ${CIRCLE_PROJECT_REPONAME}:latest"
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar
  Compile:
    executor: docker-builder
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: "Load archived Docker image"
          command: "docker load -i /tmp/workspace/image.tar"
      - run:
          name: "Compiling"
          command: "docker run ${CIRCLE_PROJECT_REPONAME}:latest ./mvnw clean compile"
  Test:
    executor: docker-builder
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: "Load archived Docker image"
          command: "docker load -i /tmp/workspace/image.tar"
      - run:
          name: "Testing"
          command: "docker run ${CIRCLE_PROJECT_REPONAME}:latest ./mvnw clean test"

  Package:
    executor: docker-builder
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "Install Heroku"
          command: "curl https://cli-assets.heroku.com/install.sh | sh"
      - run:
          name: "Renaming Dockerfile"
          command: "mv Dockerfile.runtime Dockerfile"
      - run:
          name: "Logging to heroku container registry"
          command: "heroku container:login"
      - run:
          name: "pushing image in to heroku registry"
          command: "heroku container:push web -a ${HEROKU_APP_NAME}"
  Security:
    executor: docker-builder
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: "Load archived Docker image"
          command: "docker load -i /tmp/workspace/image.tar"
      - run:
          name: "Packaging application"
          command: "docker run  -v $PWD:/app-artifact ${CIRCLE_PROJECT_REPONAME}:latest ./mvnw clean package -Dmaven.test.skip=true  && mv target/ /app-artifact"
      - run:
          name: "Running security checks"
          command:  "cd app-artifact && docker run --rm -v $PWD:/target hawkeyesec/scanner-cli"
  Deploy:
    executor: docker-builder
    steps:
      - setup_remote_docker
      - run:
          name: "Install Heroku"
          command: "curl https://cli-assets.heroku.com/install.sh | sh"
      - run:
          name: "Logging to heroku container registry"
          command: "heroku container:login"
      - run:
          name: "Releasing the newest image in the registry"
          command: "heroku container:release web -a ${HEROKU_APP_NAME}"

# Orchestrate or schedule a set of jobs, see https://circleci.com/docs/2.0/workflows/
workflows:
  version: 2
  CI:
    jobs:
      - BuildImage
      - Compile:
          requires:
            - BuildImage
      - Test:
          requires:
            - Compile
      - Package:
          requires:
            - Test
      - Security:
          requires:
            - Test
      - Deploy:
          requires:
            - Security
            - Package
          filters:
            branches:
              only: master