# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

executors:
  docker-builder:
    environment:
      IMAGE_NAME: "${CIRCLE_PROJECT_REPONAME}:${CIRCLE_BUILD_NUM}"
    docker:
      - image: circleci/buildpack-deps:stretch

jobs:
  BuildImage:
    executor: docker-builder
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "Building project image"
          command: "docker build -t ${IMAGE_NAME} ."
      - run:
          name: "Archive Docker image"
          command: "docker save -o image.tar ${IMAGE_NAME}"
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar
  Compile:
    executor: docker-builder
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: "Load archived Docker image"
          command: "docker load -i /tmp/workspace/image.tar"
      - run:
          name: "Compiling"
          command: "docker run ${IMAGE_NAME} ./mvnw clean compile"
  Test:
    executor: docker-builder
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: "Load archived Docker image"
          command: "docker load -i /tmp/workspace/image.tar"
      - run:
          name: "Testing"
          command: "docker run ${IMAGE_NAME} ./mvnw clean test"

# Orchestrate or schedule a set of jobs, see https://circleci.com/docs/2.0/workflows/
workflows:
  version: 2
  CI:
    jobs:
      - BuildImage
      - Compile:
          requires:
            - BuildImage
      - Test:
          requires:
            - Compile