# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1
orbs:
  heroku: circleci/heroku@0.0.8
executors:
  docker-builder:
    docker:
      - image: circleci/buildpack-deps:stretch

jobs:
  BuildImage:
    executor: docker-builder
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "Building project image"
          command: "docker build -t ${CIRCLE_PROJECT_REPONAME}:latest ."
      - run:
          name: "Archive Docker image"
          command: "docker save -o image.tar ${CIRCLE_PROJECT_REPONAME}:latest"
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar
  Compile:
    executor: docker-builder
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: "Load archived Docker image"
          command: "docker load -i /tmp/workspace/image.tar"
      - run:
          name: "Compiling"
          command: "docker run ${CIRCLE_PROJECT_REPONAME}:latest ./mvnw clean compile"
  Test:
    executor: docker-builder
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: "Load archived Docker image"
          command: "docker load -i /tmp/workspace/image.tar"
      - run:
          name: "Testing"
          command: "docker run ${CIRCLE_PROJECT_REPONAME}:latest ./mvnw clean test"

  Package:
    executor: heroku/default
    steps:
      - checkout
      - setup_remote_docker
      - heroku/install
      - run:
          name: "Renaming Dockerfile"
          command: "mv Dockerfile.runtime Dockerfile"
      - run:
          name: "Logging to heroku container registry"
          command: "heroku container:login"
      - run:
          name: "Load archived Docker image"
          command: "docker load -i /tmp/workspace/prod-image.tar.tar"
      - run:
          name: "pushing image in to heroku registry"
          command: "heroku container:push web -a ${HEROKU_APP_NAME}"
  Deploy:
    executor: heroku/default
    steps:
      - heroku/install
      - run:
          name: "Logging to heroku container registry"
          command: "heroku container:login"
      - run:
          name: "Releasing the newest image in the registry"
          command: "heroku container:release web -a ${HEROKU_APP_NAME}"

# Orchestrate or schedule a set of jobs, see https://circleci.com/docs/2.0/workflows/
workflows:
  version: 2
  CI:
    jobs:
      - BuildImage
      - Compile:
          requires:
            - BuildImage
      - Test:
          requires:
            - Compile
      - Package:
          requires:
            - Test
      - Deploy:
          requires:
            - Package
          filters:
            branches:
              only: master